changed copy sequence to maintain root contents

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Ensure wildcards in globs match dotfiles too.
 shopt -s dotglob
@@ -10,7 +11,6 @@ indent() {
 BUILD_DIR="$1"
 CACHE_DIR="$2"
 ENV_DIR="$3"
-STAGE="$(mktemp -d)"
 
 if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
     echo "APP_BASE was not set. Aborting" | indent
@@ -18,16 +18,12 @@ if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
 fi
 APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
 
-(
-    mv "${BUILD_DIR}/${APP_BASE}" "${STAGE}" &&
-    rm -rf "${BUILD_DIR}"/* &&
-    mv "${STAGE}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
-)
+# Copy the contents of BUILD_DIR/APP_BASE into BUILD_DIR without deleting existing files
+cp -r "${BUILD_DIR}/${APP_BASE}/." "${BUILD_DIR}/"
 
 if [ $? -ne 0 ]; then
-    echo "FAILED to copy directory into place" | indent
+    echo "FAILED to copy directory contents into place" | indent
     exit 1
 fi
 
-echo "Copied ${APP_BASE} to root of app successfully" | indent
-
+echo "Copied contents of ${APP_BASE} into root of app successfully" | indent
